### ISSUE TITLE
How is this repo different than langchain_community.vectorstores.weaviate?

### ISSUE THREAD

**Issue by shashankram** [langchain-ai/langchain-weaviate#202]
Wondering if this repo is to be preferred over [langchain_community.vectorstores.weaviate](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/weaviate.py). Kindly clarify, thanks.

**Comment by hsm207** [comment]
Yes, this repo should be preferred over the one in langchain_community. This is a [partner package](https://python.langchain.com/v0.1/docs/contributing/integrations/#partner-package-in-external-repo)
